### PR TITLE
Add in data pipeline parameters

### PR DESCRIPTION
**Pull request by claireh93**
Download Scottish population data and various other parameters.

### CODE REVIEW

**Comment by claireh93** [comment]
I'm trying to add testing for the new function for downloading scottish population data from the pipeline (`parse_scottish_population`), so that codecov doesn't complain - but this is causing headaches on travis! It does seem to run fine locally though?

**Comment by richardreeve** [comment]
@claireh93 You don't need a `run_id` in the `config.yaml` files btw - it is generated automatically to make sure it's unique.

**Comment by claireh93** [comment]
Okay @richardreeve I think the try-catch statement is working here (pending some more tests)! See what you think

**Comment by claireh93** [comment]
@richardreeve possible to merge this one in now I think!

**Review by richardreeve — APPROVED** [review]
I haven't checked the R code, and I'm not sure how helpful it is to upload the metadata.yaml file, but I'm happy for you to merge this @claireh93...

**Comment by claireh93** [comment]
Hmm aliasing not working properly - I think we should revert to the previous working version for now and fix that later, as it's more of a cosmetic issue.

**Pull request merged**
