### PR TITLE
Jwscook/conributing

### PR DESCRIPTION
**Pull request by jwscook**
Added a CONTRIBUTING.md covering PRs

### CODE REVIEW

**Comment by jwscook** [comment]
Travis failed due to hanging on configuring MPI on ubuntu, but the macos job passed. It's only a markdown file after all, so I'll merge in.

Error message below:

> 650 2020-04-30 14:25:34 (14.0 MB/s) - ‘openmpi-4.0.3.tar.gz’ saved [17418534/17418534]
> 651
> 652Configuring and building OpenMPI
> 653
> 654
> 655No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
> 656Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
> 657
> 658The build has been terminated

**Comment by jwscook** [comment]
I'll hold off merging until the "Simulation.jl" team has been renamed to "Simulation.jl-admins" and altered CONTRIBUTING.md to reflect that this team should be the reviewer.

**Comment by richardreeve** [comment]
Do we want to mention contribution licensing from ScottishCovidResponse/SCRCIssueTracking#60 here?

Also, I’ve just discovered that you can make shortcuts [(autolink references)](https://github.com/ScottishCovidResponse/Simulation.jl/settings/key_links) to make the above SCRC-60 or something... do we want to do that to avoid all that text?

**Comment by jwscook** [comment]
Good spot. I've created the auto link as per your suggestion `SCRC-123` and will update the .md

**Comment by jwscook** [comment]
We've pivoted to PRing into `dev` hence the change to #8

**Pull request merged**
