### PR TITLE
Ep/jlso

### PR DESCRIPTION
**Pull request by jwscook**
Somehow this went wrong in #7 -  possibly due to me being slow to get to the PR and dev already becoming rusted.

### CODE REVIEW

**Comment by claireh93** [comment]
Does it matter that one of the travis builds failed here?

**Comment by jwscook** [comment]
continuous-integration/travis-ci/push used `[925886fa] + OnlineStatsBase v1.3.0` & failed as expected
continuous-integration/travis-ci/pr used `[925886fa] + OnlineStatsBase v1.2.8` & passed as expected

Why would they use different versions?!

**Comment by jwscook** [comment]
@claireh93 I'm worried it will merge a breakage into `dev` because the Project.toml is clearly wrong:

https://github.com/ScottishCovidResponse/Simulation.jl/pull/13/files#diff-910a7b3ca0075d545dcec45cb7335ca9R49-R50 

vs
 
https://github.com/ScottishCovidResponse/Simulation.jl/blob/83c8dac387f44020f0917ce5797099b5cec5915e/Project.toml#L50

**Comment by jwscook** [comment]
I amended the last commit message, and did a `git push --force-with-lease` onto the upstream/ep/jslo branch.

**Comment by jwscook** [comment]
I was hoping it would refresh the `diff`, but it hasn't. More info here https://github.com/isaacs/github/issues/750 and in particular here https://github.com/isaacs/github/issues/750#issuecomment-394027509

**Comment by claireh93** [comment]
Hmm strange! Doesn't look like it incorporated recent changes to Phylo or OnlineStatsBase. I'm not sure I know what force-with-lease means exactly, but hopefully it helped?

**Comment by jwscook** [comment]
The `--force-with-lease` allowed me to push the amended commit message, which in turn triggered the travis build again.

**Comment by jwscook** [comment]
Can confirm tests passed after merge when run on my own machine.

**Pull request merged**
