### PR TITLE
Updates to test files following new structure and incorporating updat…

### PR DESCRIPTION
**Pull request by claireh93**
…es to other packages (e.g. Unitful has its own year unit now). Tests currently pass on 1.4.1, with Phylo@0.3.3 and OnlineStats@1.2.0

### CODE REVIEW

**Comment by jwscook** [comment]
What does your `Manifest.toml` look like when you get these tests to pass @claireh93 ?

**Comment by jwscook** [comment]
When I try to run it:

```julia
(env) pkg> test Simulation#travis-testing-fix
    Testing Simulation
Status `/tmp/jl_dk1q62/Manifest.toml`
  [1520ce14] AbstractTrees v0.3.3
  [79e6a3ab] Adapt v1.0.1
  [c9ce4bd3] ArchGDAL v0.3.2
  [7d9fca2a] Arpack v0.4.0
  [68821587] Arpack_jll v3.5.0+3
  [4fba245c] ArrayInterface v2.8.5
  [69666777] Arrow v0.2.4
  [13072b0f] AxisAlgorithms v1.0.0
  [39de3d68] AxisArrays v0.4.3
  [9e28174c] BinDeps v1.0.1
  [b99e7846] BinaryProvider v0.5.8
  [a74b3585] Blosc v0.6.0
  [6e34b625] Bzip2_jll v1.0.6+2
  [fa961155] CEnum v0.2.0
  [631607c0] CMake v1.2.0
  [d5fb7624] CMakeWrapper v0.2.3
  [49dc2e85] Calculus v0.5.1
  [324d7699] CategoricalArrays v0.7.7
  [944b1d66] CodecZlib v0.6.0
  [35d6a980] ColorSchemes v3.9.0
  [3da002f7] ColorTypes v0.10.2
  [5ae59095] Colors v0.12.0
  [861a8166] Combinatorics v1.0.1
  [bbf7d656] CommonSubexpressions v0.2.0
  [34da2185] Compat v2.2.0
  [e66e0078] CompilerSupportLibraries_jll v0.3.3+0
  [8f4d0f93] Conda v1.4.1
  [a9693cdc] CondaBinDeps v0.2.0
  [187b0558] ConstructionBase v1.0.0
  [d38c429a] Contour v0.5.2
  [d58978e5] Dagger v0.8.0
  [9a962f9c] DataAPI v1.2.0
  [a93c6f00] DataFrames v0.20.2
  [1313f7d8] DataFramesMeta v0.5.0
  [9a8bc11e] DataStreams v0.4.2
  [864edb3b] DataStructures v0.17.13
  [e2d170a0] DataValueInterfaces v1.0.0
  [e7dc6d0d] DataValues v0.4.13
  [163ba53b] DiffResults v1.0.2
  [b552c78f] DiffRules v1.0.1
  [3c3547ce] DiskArrays v0.2.3
  [b4f34e82] Distances v0.8.2
  [31c24e10] Distributions v0.23.2
  [d3d5718d] Diversity v0.4.6
  [ffbed154] DocStringExtensions v0.8.1
  [497a8b3b] DoubleFloats v1.1.8
  [a58aae7d] EcoBase v0.1.3
  [da5c29d0] EllipsisNotation v0.4.0
  [e2ba6199] ExprTools v0.1.1
  [8f5d6c58] EzXML v1.1.0
  [c87230d0] FFMPEG v0.3.0
  [b22a6f82] FFMPEG_jll v4.1.0+2
  [becb17da] Feather v0.5.5
  [5789e2e9] FileIO v1.2.4
  [1a297f60] FillArrays v0.8.7
  [6a86dc24] FiniteDiff v2.3.0
  [53c48c17] FixedPointNumbers v0.8.0
  [53afe959] FlatBuffers v0.5.4
  [59287772] Formatting v0.4.1
  [f6369f11] ForwardDiff v0.10.10
  [d7e528f0] FreeType2_jll v2.10.1+2
  [559328eb] FriBidi_jll v1.0.5+2
  [add2ef01] GDAL v1.1.0
  [a7073274] GDAL_jll v3.0.4+0
  [d604d12d] GEOS_jll v3.8.1+0
  [28b8d3ca] GR v0.48.0
  [01680d73] GenericSVD v0.3.0
  [c145ed77] GenericSchur v0.4.0
  [68eda718] GeoFormatTypes v0.3.0
  [cf35fbd7] GeoInterface v0.5.4
  [4d00f742] GeometryTypes v0.8.2
  [c27321d9] Glob v1.3.0
  [19dc6840] HCubature v1.4.0
  [f67ccb44] HDF5 v0.13.1
  [0234f1f7] HDF5_jll v1.10.5+5
  [6deec6e2] IndexedTables v0.12.6
  [a98d9a8b] Interpolations v0.12.9
  [8197267c] IntervalSets v0.5.0
  [d8418881] Intervals v1.1.0
  [41ab1584] InvertedIndices v1.0.0
  [c8e1da08] IterTools v1.3.0
  [1c8ee90f] IterableTables v1.0.0
  [82899510] IteratorInterfaceExtensions v1.0.0
  [4138dd39] JLD v0.10.0
  [682c06a0] JSON v0.21.0
  [a93385a2] JuliaDB v0.13.0
  [c1c5ebd0] LAME_jll v3.100.0+0
  [7f8f8fb0] LearnBase v0.2.2
  [deac9b47] LibCURL_jll v7.68.0+0
  [29816b5a] LibSSH2_jll v1.9.0+1
  [dd192d2f] LibVPX_jll v1.8.1+1
  [94ce4f54] Libiconv_jll v1.16.0+2
  [d3d80556] LineSearches v7.0.1
  [30fc2ffe] LossFunctions v0.5.1
  [da04e1cc] MPI v0.13.1
  [c8ffd9c3] MbedTLS_jll v2.16.0+2
  [442fdcdd] Measures v0.3.1
  [f9f48841] MemPool v0.2.0
  [e1d29d7a] Missings v0.4.3
  [78c3b35d] Mocking v0.7.1
  [d41bc354] NLSolversBase v7.6.1
  [77ba4419] NaNMath v0.3.3
  [30363a11] NetCDF v0.10.2
  [4d1e1d77] Nullables v1.0.0
  [6fe1bfb0] OffsetArrays v1.0.4
  [e7412a2a] Ogg_jll v1.3.3+0
  [a15396b6] OnlineStats v1.2.0
  [925886fa] OnlineStatsBase v1.2.8
  [4536629a] OpenBLAS_jll v0.3.9+2
  [458c3c95] OpenSSL_jll v1.1.1+2
  [efe28fd5] OpenSpecFun_jll v0.5.3+3
  [429524aa] Optim v0.20.1
  [91d4177d] Opus_jll v1.3.1+0
  [bac558e1] OrderedCollections v1.1.0
  [90014a1f] PDMats v0.9.12
  [58948b4f] PROJ_jll v6.3.0+0
  [d96e819e] Parameters v0.12.0
  [69de0a69] Parsers v1.0.2
  [06bb1623] PenaltyFunctions v0.1.2
  [aea672f4] Phylo v0.3.3
  [ccf2f8ad] PlotThemes v2.0.0
  [995b91a9] PlotUtils v1.0.0
  [91a5bcdd] Plots v0.27.1
  [f27b6e38] Polynomials v0.8.0
  [2dfb63ee] PooledArrays v0.5.3
  [85a6dd25] PositiveFactorizations v0.2.3
  [1fd47b50] QuadGK v2.3.1
  [be4d8f0f] Quadmath v0.5.2
  [6f49c342] RCall v0.13.5
  [9ae346a0] RandomBooleanMatrices v0.1.1
  [e6cf234a] RandomNumbers v1.4.0
  [b3c3ace0] RangeArrays v0.3.2
  [c84ed2f1] Ratios v0.4.0
  [3cdcf5f2] RecipesBase v0.8.0
  [189a3867] Reexport v0.2.0
  [ae029012] Requires v0.5.2
  [79098fc4] Rmath v0.6.1
  [f50d1b31] Rmath_jll v0.2.2+0
  [76ed43ae] SQLite_jll v3.31.1+0
  [1277b4bf] ShiftedArrays v1.0.0
  [992d4aef] Showoff v0.3.1
  [ed2dc23b] Simulation v0.0.0 #epi (https://github.com/ScottishCovidResponse/Simulation.jl.git)
  [a2af1166] SortingAlgorithms v0.3.1
  [348f2d5d] SpatialEcology v0.9.4
  [276daf66] SpecialFunctions v0.10.0
  [90137ffa] StaticArrays v0.12.2
  [2913bbd2] StatsBase v0.32.2
  [4c63d2b9] StatsFuns v0.9.4
  [3eaba693] StatsModels v0.6.11
  [09ab397b] StructArrays v0.4.3
  [7522ee7d] SweepOperator v0.3.0
  [3783bdb8] TableTraits v1.0.0
  [382cd787] TableTraitsUtils v1.0.1
  [bd369af6] Tables v1.0.4
  [e0df1984] TextParse v1.0.0
  [f269a46b] TimeZones v1.1.1
  [0796e94c] Tokenize v0.5.8
  [3bb67fe8] TranscodingStreams v0.9.5
  [30578b45] URIParser v0.4.1
  [1986cc42] Unitful v1.1.0
  [81def892] VersionParsing v1.2.0
  [ea10d353] WeakRefStrings v0.6.2
  [1b915085] WinReg v0.3.1
  [efce3f68] WoodburyMatrices v0.5.2
  [02c8fc9c] XML2_jll v2.9.9+4
  [83775a58] Zlib_jll v1.2.11+9
  [0ac62f75] libass_jll v0.14.0+1
  [f638f0a6] libfdk_aac_jll v0.1.6+1
  [f27f6e37] libvorbis_jll v1.3.6+2
  [1270edf5] x264_jll v2019.5.25+1
  [dfaa095f] x265_jll v3.0.0+0
  [2a0f44e3] Base64 
  [ade2ca70] Dates 
  [8bb1440f] DelimitedFiles 
  [8ba89e20] Distributed 
  [9fa8497b] Future 
  [b77e0a4c] InteractiveUtils 
  [76f85450] LibGit2 
  [8f399da3] Libdl 
  [37e2e46d] LinearAlgebra 
  [56ddb016] Logging 
  [d6f4376e] Markdown 
  [a63ad114] Mmap 
  [44cfe95a] Pkg 
  [de0858da] Printf 
  [9abbd945] Profile 
  [3fa0cd96] REPL 
  [9a3f8284] Random 
  [ea8e919c] SHA 
  [9e88b42a] Serialization 
  [1a1011a3] SharedArrays 
  [6462fe0b] Sockets 
  [2f01184e] SparseArrays 
  [10745b16] Statistics 
  [4607b0f0] SuiteSparse 
  [8dfed614] Test 
  [cf7118a7] UUIDs 
  [4ec0a83e] Unicode 
[ Info: Running tests for files:
    = AbioticEnv.jl
    = AdditionalDiversity.jl
    = Demographics.jl
    = Ecosystem.jl
    = Energy.jl
    = EpiEnv.jl
    = EpiGenerate.jl
    = EpiHelper.jl
    = EpiLandscape.jl
    = EpiList.jl
    = EpiParams.jl
    = EpiSystem.jl
    = EpiTraits.jl
    = Generate.jl
    = HabitatUpdate.jl
    = Helper.jl
    = Movement.jl
    = SpeciesList.jl
    = TraitRelationship.jl
    = Traits.jl

[ Info: Running tests...
    * Testing AbioticEnv.jl ...
Creating Diversity to Phylo interface...

    * Testing AdditionalDiversity.jl ...
Creating Phylo RCall interface...
┌ Warning: RCall.jl: Loading required package: ape
│ Loading required package: vegan
│ Loading required package: permute
│ Loading required package: lattice
│ This is vegan 2.5-6
│ Loading required package: nlme
└ @ RCall ~/.julia/packages/RCall/paaBQ/src/io.jl:113

    * Testing Demographics.jl ...

    * Testing Ecosystem.jl ...

    * Testing Energy.jl ...

    * Testing EpiEnv.jl ...

    * Testing EpiGenerate.jl ...
ERROR: LoadError: LoadError: MethodError: no method matching SIRGrowth{Unitful.FreeUnits{(d^-1,),𝐓^-1,nothing}}(::Array{Quantity{Float64,𝐓^-1,Unitful.FreeUnits{(d^-1,),𝐓^-1,nothing}},1}, ::Array{Quantity{Float64,𝐓^-1,Unitful.FreeUnits{(d^-1,),𝐓^-1,nothing}},1}, ::Quantity{Float64,𝐓^-1,Unitful.FreeUnits{(d^-1,),𝐓^-1,nothing}}, ::Quantity{Float64,𝐓^-1,Unitful.FreeUnits{(d^-1,),𝐓^-1,nothing}})
Closest candidates are:
  SIRGrowth{Unitful.FreeUnits{(d^-1,),𝐓^-1,nothing}}(::Array{Quantity{Float64,𝐓^-1,U},1}, ::Array{Quantity{Float64,𝐓^-1,U},1}, ::Quantity{Float64,𝐓^-1,U}, ::Quantity{Float64,𝐓^-1,U}, ::Quantity{Float64,𝐓^-1,U}, ::Quantity{Float64,𝐓^-1,U}) where U<:Unitful.Units at /root/.julia/packages/Simulation/37EIo/src/Epidemiology/EpiParams.jl:14
Stacktrace:
 [1] TestEpiSystem() at /root/.julia/packages/Simulation/37EIo/test/TestCases.jl:45
 [2] top-level scope at /root/.julia/packages/Simulation/37EIo/test/test_EpiGenerate.jl:10
 [3] include(::String) at ./client.jl:439
 [4] top-level scope at /root/.julia/packages/Simulation/37EIo/test/runtests.jl:20
 [5] include(::String) at ./client.jl:439
 [6] top-level scope at none:6
in expression starting at /root/.julia/packages/Simulation/37EIo/test/test_EpiGenerate.jl:10
in expression starting at /root/.julia/packages/Simulation/37EIo/test/runtests.jl:17
ERROR: Package Simulation errored during testing
```

**Comment by claireh93** [comment]
```(@v1.4) pkg> test Simulation
    Testing Simulation
Status `/private/var/folders/j2/f10q88jd35l1f5nc711p7hwc0000gn/T/jl_8VmytA/Manifest.toml`
  [1520ce14] AbstractTrees v0.3.3
  [79e6a3ab] Adapt v1.0.1
  [c9ce4bd3] ArchGDAL v0.3.2
  [7d9fca2a] Arpack v0.4.0
  [68821587] Arpack_jll v3.5.0+3
  [4fba245c] ArrayInterface v2.8.5
  [69666777] Arrow v0.2.4
  [13072b0f] AxisAlgorithms v1.0.0
  [39de3d68] AxisArrays v0.4.3
  [9e28174c] BinDeps v1.0.1
  [b99e7846] BinaryProvider v0.5.8
  [a74b3585] Blosc v0.6.0
  [6e34b625] Bzip2_jll v1.0.6+2
  [fa961155] CEnum v0.2.0
  [631607c0] CMake v1.2.0
  [d5fb7624] CMakeWrapper v0.2.3
  [49dc2e85] Calculus v0.5.1
  [324d7699] CategoricalArrays v0.7.7
  [944b1d66] CodecZlib v0.6.0
  [35d6a980] ColorSchemes v3.9.0
  [3da002f7] ColorTypes v0.10.2
  [5ae59095] Colors v0.12.0
  [861a8166] Combinatorics v1.0.1
  [bbf7d656] CommonSubexpressions v0.2.0
  [34da2185] Compat v2.2.0
  [e66e0078] CompilerSupportLibraries_jll v0.3.3+0
  [8f4d0f93] Conda v1.4.1
  [a9693cdc] CondaBinDeps v0.2.0
  [187b0558] ConstructionBase v1.0.0
  [d38c429a] Contour v0.5.2
  [d58978e5] Dagger v0.8.0
  [9a962f9c] DataAPI v1.2.0
  [a93c6f00] DataFrames v0.20.2
  [1313f7d8] DataFramesMeta v0.5.0
  [9a8bc11e] DataStreams v0.4.2
  [864edb3b] DataStructures v0.17.13
  [e2d170a0] DataValueInterfaces v1.0.0
  [e7dc6d0d] DataValues v0.4.13
  [163ba53b] DiffResults v1.0.2
  [b552c78f] DiffRules v1.0.1
  [3c3547ce] DiskArrays v0.2.3
  [b4f34e82] Distances v0.8.2
  [31c24e10] Distributions v0.23.2
  [d3d5718d] Diversity v0.4.6
  [ffbed154] DocStringExtensions v0.8.1
  [497a8b3b] DoubleFloats v1.1.8
  [a58aae7d] EcoBase v0.1.3
  [da5c29d0] EllipsisNotation v0.4.0
  [e2ba6199] ExprTools v0.1.1
  [8f5d6c58] EzXML v1.1.0
  [c87230d0] FFMPEG v0.3.0
  [b22a6f82] FFMPEG_jll v4.1.0+2
  [becb17da] Feather v0.5.5
  [5789e2e9] FileIO v1.2.4
  [1a297f60] FillArrays v0.8.7
  [6a86dc24] FiniteDiff v2.3.0
  [53c48c17] FixedPointNumbers v0.8.0
  [53afe959] FlatBuffers v0.5.4
  [59287772] Formatting v0.4.1
  [f6369f11] ForwardDiff v0.10.10
  [d7e528f0] FreeType2_jll v2.10.1+2
  [559328eb] FriBidi_jll v1.0.5+2
  [add2ef01] GDAL v1.1.0
  [a7073274] GDAL_jll v3.0.4+0
  [d604d12d] GEOS_jll v3.8.1+0
  [28b8d3ca] GR v0.48.0
  [01680d73] GenericSVD v0.3.0
  [c145ed77] GenericSchur v0.4.0
  [68eda718] GeoFormatTypes v0.3.0
  [cf35fbd7] GeoInterface v0.5.4
  [4d00f742] GeometryTypes v0.8.2
  [c27321d9] Glob v1.3.0
  [19dc6840] HCubature v1.4.0
  [f67ccb44] HDF5 v0.13.1
  [0234f1f7] HDF5_jll v1.10.5+5
  [6deec6e2] IndexedTables v0.12.6
  [a98d9a8b] Interpolations v0.12.9
  [8197267c] IntervalSets v0.5.0
  [d8418881] Intervals v1.1.0
  [41ab1584] InvertedIndices v1.0.0
  [c8e1da08] IterTools v1.3.0
  [1c8ee90f] IterableTables v1.0.0
  [82899510] IteratorInterfaceExtensions v1.0.0
  [4138dd39] JLD v0.10.0
  [682c06a0] JSON v0.21.0
  [a93385a2] JuliaDB v0.13.0
  [c1c5ebd0] LAME_jll v3.100.0+0
  [7f8f8fb0] LearnBase v0.2.2
  [deac9b47] LibCURL_jll v7.68.0+0
  [29816b5a] LibSSH2_jll v1.9.0+1
  [dd192d2f] LibVPX_jll v1.8.1+1
  [94ce4f54] Libiconv_jll v1.16.0+2
  [d3d80556] LineSearches v7.0.1
  [30fc2ffe] LossFunctions v0.5.1
  [da04e1cc] MPI v0.13.1
  [c8ffd9c3] MbedTLS_jll v2.16.0+2
  [442fdcdd] Measures v0.3.1
  [f9f48841] MemPool v0.2.0
  [e1d29d7a] Missings v0.4.3
  [78c3b35d] Mocking v0.7.1
  [d41bc354] NLSolversBase v7.6.1
  [77ba4419] NaNMath v0.3.3
  [30363a11] NetCDF v0.10.2
  [4d1e1d77] Nullables v1.0.0
  [6fe1bfb0] OffsetArrays v1.0.4
  [e7412a2a] Ogg_jll v1.3.3+0
  [a15396b6] OnlineStats v1.2.0
  [925886fa] OnlineStatsBase v1.2.8
  [4536629a] OpenBLAS_jll v0.3.9+2
  [458c3c95] OpenSSL_jll v1.1.1+2
  [efe28fd5] OpenSpecFun_jll v0.5.3+3
  [429524aa] Optim v0.20.1
  [91d4177d] Opus_jll v1.3.1+0
  [bac558e1] OrderedCollections v1.1.0
  [90014a1f] PDMats v0.9.12
  [58948b4f] PROJ_jll v6.3.0+0
  [d96e819e] Parameters v0.12.0
  [69de0a69] Parsers v1.0.2
  [06bb1623] PenaltyFunctions v0.1.2
  [aea672f4] Phylo v0.3.3
  [ccf2f8ad] PlotThemes v2.0.0
  [995b91a9] PlotUtils v1.0.0
  [91a5bcdd] Plots v0.27.1
  [f27b6e38] Polynomials v0.8.0
  [2dfb63ee] PooledArrays v0.5.3
  [85a6dd25] PositiveFactorizations v0.2.3
  [1fd47b50] QuadGK v2.3.1
  [be4d8f0f] Quadmath v0.5.2
  [6f49c342] RCall v0.13.5
  [9ae346a0] RandomBooleanMatrices v0.1.1
  [e6cf234a] RandomNumbers v1.4.0
  [b3c3ace0] RangeArrays v0.3.2
  [c84ed2f1] Ratios v0.4.0
  [3cdcf5f2] RecipesBase v0.8.0
  [189a3867] Reexport v0.2.0
  [ae029012] Requires v0.5.2
  [79098fc4] Rmath v0.6.1
  [f50d1b31] Rmath_jll v0.2.2+0
  [76ed43ae] SQLite_jll v3.31.1+0
  [1277b4bf] ShiftedArrays v1.0.0
  [992d4aef] Showoff v0.3.1
  [ed2dc23b] Simulation v0.0.0 [`~/Documents/PhD/GIT/Simulation`]
  [a2af1166] SortingAlgorithms v0.3.1
  [348f2d5d] SpatialEcology v0.9.4
  [276daf66] SpecialFunctions v0.10.0
  [90137ffa] StaticArrays v0.12.2
  [2913bbd2] StatsBase v0.32.2
  [4c63d2b9] StatsFuns v0.9.4
  [3eaba693] StatsModels v0.6.11
  [09ab397b] StructArrays v0.4.3
  [7522ee7d] SweepOperator v0.3.0
  [3783bdb8] TableTraits v1.0.0
  [382cd787] TableTraitsUtils v1.0.1
  [bd369af6] Tables v1.0.4
  [e0df1984] TextParse v1.0.0
  [f269a46b] TimeZones v1.1.1
  [0796e94c] Tokenize v0.5.8
  [3bb67fe8] TranscodingStreams v0.9.5
  [30578b45] URIParser v0.4.1
  [1986cc42] Unitful v1.1.0
  [81def892] VersionParsing v1.2.0
  [ea10d353] WeakRefStrings v0.6.2
  [1b915085] WinReg v0.3.1
  [efce3f68] WoodburyMatrices v0.5.2
  [02c8fc9c] XML2_jll v2.9.9+4
  [83775a58] Zlib_jll v1.2.11+9
  [0ac62f75] libass_jll v0.14.0+1
  [f638f0a6] libfdk_aac_jll v0.1.6+1
  [f27f6e37] libvorbis_jll v1.3.6+2
  [1270edf5] x264_jll v2019.5.25+1
  [dfaa095f] x265_jll v3.0.0+0
  [2a0f44e3] Base64 
  [ade2ca70] Dates 
  [8bb1440f] DelimitedFiles 
  [8ba89e20] Distributed 
  [9fa8497b] Future 
  [b77e0a4c] InteractiveUtils 
  [76f85450] LibGit2 
  [8f399da3] Libdl 
  [37e2e46d] LinearAlgebra 
  [56ddb016] Logging 
  [d6f4376e] Markdown 
  [a63ad114] Mmap 
  [44cfe95a] Pkg 
  [de0858da] Printf 
  [9abbd945] Profile 
  [3fa0cd96] REPL 
  [9a3f8284] Random 
  [ea8e919c] SHA 
  [9e88b42a] Serialization 
  [1a1011a3] SharedArrays 
  [6462fe0b] Sockets 
  [2f01184e] SparseArrays 
  [10745b16] Statistics 
  [4607b0f0] SuiteSparse 
  [8dfed614] Test 
  [cf7118a7] UUIDs 
  [4ec0a83e] Unicode 
[ Info: Running tests for files:
    = AbioticEnv.jl
    = AdditionalDiversity.jl
    = Demographics.jl
    = Ecosystem.jl
    = Energy.jl
    = EpiEnv.jl
    = EpiGenerate.jl
    = EpiHelper.jl
    = EpiLandscape.jl
    = EpiList.jl
    = EpiParams.jl
    = EpiSystem.jl
    = EpiTraits.jl
    = Generate.jl
    = HabitatUpdate.jl
    = Helper.jl
    = Movement.jl
    = SpeciesList.jl
    = TraitRelationship.jl
    = Traits.jl

[ Info: Running tests...
    * Testing AbioticEnv.jl ...
Creating Diversity to Phylo interface...

    * Testing AdditionalDiversity.jl ...
Creating Phylo RCall interface...
┌ Warning: RCall.jl: Loading required package: ape
│ Loading required package: vegan
│ Loading required package: permute
│ Loading required package: lattice
│ This is vegan 2.5-6
│ Loading required package: nlme
└ @ RCall ~/.julia/packages/RCall/paaBQ/src/io.jl:113

    * Testing Demographics.jl ...

    * Testing Ecosystem.jl ...

    * Testing Energy.jl ...

    * Testing EpiEnv.jl ...

    * Testing EpiGenerate.jl ...

    * Testing EpiHelper.jl ...
..............................
    * Testing EpiLandscape.jl ...

    * Testing EpiList.jl ...

    * Testing EpiParams.jl ...

    * Testing EpiSystem.jl ...

    * Testing EpiTraits.jl ...

    * Testing Generate.jl ...

    * Testing HabitatUpdate.jl ...

    * Testing Helper.jl ...
..........
    * Testing Movement.jl ...

    * Testing SpeciesList.jl ...

    * Testing TraitRelationship.jl ...

    * Testing Traits.jl ...

    Testing Simulation tests passed ```

**Comment by claireh93** [comment]
Hmm that's strange, looks like the errors I got before I made the updates to how the epi tests run

**Comment by jwscook** [comment]
Got it! These are the 3 packages with version constraint that matter today, at least. Tomorrow I'll put the `[compat]` section in the `Project.toml` to sort it out, unless someone beats me to it.

```julia
pkg> add Phylo@0.3.3
pkg> add OnlineStats@1.2.0
pkg> add DataAPI@1.2.0
```
These are the remaining differences, which don't appear to matter as all the tests run and pass!

```bash
shell> diff james.txt claire.txt
19a20
>   [35d6a980] ColorSchemes v3.9.0
120,122c121,123
<   [ccf2f8ad] PlotThemes v1.0.3
<   [995b91a9] PlotUtils v0.6.5
<   [91a5bcdd] Plots v0.29.9
---
>   [ccf2f8ad] PlotThemes v2.0.0
>   [995b91a9] PlotUtils v1.0.0
>   [91a5bcdd] Plots v0.27.1
141c142
<   [ed2dc23b] Simulation v0.0.0 [`/Simulation.jl`]
---
>   [ed2dc23b] Simulation v0.0.0 [`~/Documents/PhD/GIT/Simulation`]
171d171
< 
```

**Comment by AlexRobson** [comment]
Confirmed for me too adding these versions to Project.toml. I'll push these changes through and revisit the travis side of things (expect I need to add in the R package)

**Pull request merged**
