### PR TITLE
Add plot recipes for common plots

### PR DESCRIPTION
**Pull request by sdl1**
Addresses https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/2

Adds two plot recipes, wrapping up the existing plots in the examples:
- `plot_epidynamics`: Plot the spatially-summed dynamics over time. This can take in a keyword argument indicating which compartments to consolidate.
- `plot_epiheatmaps`: Plots spatial heatmaps at several timesteps. Currently only works for a single specified compartment

We could improve/generalise the above once we figure out indexing issues (e.g.  https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/281)

Example usage:

### Plot dynamics for all the compartments
```julia
plot_epidynamics(epi, abuns)
```
Screenshot 2020-05-28 at 12 45 54

### Plot dynamics for custom categories
```julia
category_map = (
    "Susceptible" => cat_idx[:, 1],
    "Exposed" => cat_idx[:, 2],
    "Asymptomatic" => cat_idx[:, 3],
    "Symptomatic" => cat_idx[:, 4],
    "Hospital" => cat_idx[:, 5],
    "Recovered" => cat_idx[:, 6],
    "Deaths" => cat_idx[:, 7],
)
plot_epidynamics(epi, abuns; category_map=category_map)
```
Screenshot 2020-05-28 at 12 49 05

### Plot heatmaps
```julia
plot_epiheatmaps(epi, abuns; compartment="Exposed", steps=[1, 7, 14, 21], clim=(0, 900))
```
Screenshot 2020-05-29 at 12 02 33

### CODE REVIEW

**Comment by claireh93** [comment]
This looks great @sdl1! I was just wondering if we could have the heatmaps rotated to be the right way up for Scotland? But otherwise this looks good to go!

**Comment by claireh93** [comment]
These look excellent - sorry I think my last merge has created some conflicts for you but hopefully they are not too severe!

**Comment by sdl1** [comment]
No problem! I think I've resolved them now

**Comment by claireh93** [comment]
Ah so I think what might need to be changed is sections referring to `epi.epilist.names` because now the `epilist` is divided into `epilist.human` and `epilist.virus` each with their own name vector. For now we can just assume we want to plot the human categories, but later we might want to add functionality to see the virus trajectory.

**Comment by sdl1** [comment]
Hmm the examples don't work for me any more, this line errors I think because `samp` has zeros in it:
```julia
virus(epi.abundances)[1, samp] .= 100 # Virus pop
```
any ideas?

**Comment by claireh93** [comment]
Ahh it's because we removed the 1:N_cells from the sample() call in #40, which now I think about it is doing something completely different! Would you mind putting them back in again?
```julia
samp = sample(1:N_cells, weights(1.0 .* epi.abundances.matrix[1, :]), 100)
```

**Comment by sdl1** [comment]
Ok cool, I fixed the sampling and changed it to `epi.epilist.human.names` (this works since `abuns` only stores the human compartments, I think?)

**Comment by richardreeve** [comment]
Apologies for that. My fault - I think it's a bug in `sample()` that it only works with weights on their own when you only want a single sample, but there you go...

**Review by richardreeve — APPROVED** [review]
~If it's possible to easily set the heatmap so it is on the same scale for each subplot, please do that. Otherwise this is good to merge.~ I've just seen that you can do this with `clim=c(0,100)`. I think this is good to go once the conflicts are resolved.

**Pull request merged**
