### PR TITLE
set Python ENV in julia before build

### PR DESCRIPTION
**Pull request by jwscook**
Appveyor is broken e.g. https://ci.appveyor.com/project/richardreeve/simulation-jl/builds/34781015/job/3p9vdqyocco3j44x I think due to python problems.

### CODE REVIEW

**Comment by richardreeve** [comment]
@jwscook - sadly it's still breaking when it fails to find pip on Windows...

**Comment by richardreeve** [comment]
Fixes ScottishCovidResponse/SCRCIssueTracking#350

**Comment by richardreeve** [comment]
Assuming this works, we could obviously also remove the `allow_failures` from the appveyor script too...

**Comment by jwscook** [comment]
Looks like it'll help to get SimulationData.jl building and passing on Appveyor first.

**Comment by jwscook** [comment]
I couldn't get appveyor running on SimulationData.jl, see https://github.com/ScottishCovidResponse/SimulationData.jl/pull/28, so won't get this one working either.

**Pull request closed without merging**
