### PR TITLE
Age structure

### PR DESCRIPTION
**Pull request by claireh93**
First pass at including age structure in the model. All original examples should run as they were, but now there is an optional flag for age categories when EpiList and transition matrices are created. Included a test for SIS model that runs different numbers of age categories and checks the summed results are the same each time.

Note: I have also reshuffled the code for creating transition matrices so that they only include the human categories - hence some changes to the update loops that may be relevant to ScottishCovidResponse/SCRCIssueTracking#148

### CODE REVIEW

**Comment by richardreeve** [comment]
I'm not completely sure about this as it stands, and I think it would be better - certainly easier to check - if @AlexRobson had dealt with SCRC-148 before we merge it...

**Comment by AlexRobson** [comment]
I looked over this briefly earlier but couldn't see any dependency on 148. 

I have a proposal for 148 that I'll be pushing shortly. 

EDIT: To clarify: I mean in terms of building around a virus matrix or human abundancy matricies. I can rebase onto these changes if this is blocking.

**Comment by richardreeve** [comment]
I just meant it’ll be easier for me to tell if this is right once you’ve taken the virus stuff out, so the indices for the human abundance matrices are all indexed sensibly.

**Comment by claireh93** [comment]
The indexing is a bit confusing as it stands - it will certainly be cleaner once 148 is through for sure!

**Review by richardreeve — APPROVED** [review]

**Pull request merged**
