### PR TITLE
removed allocations, minor speed gain in calc_lookup_moves!, remove unncessary rand calls, speed up here and there

### PR DESCRIPTION
**Pull request by jwscook**
SCRC-349

Make good improvements to `classupdate!` but only minor speed gain in `calc_lookup_moves!`. See
https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/345 for failed attempt to speed it up by sorting the vectors in `lookup` to make access of `epi.epienv.active` faster.

### CODE REVIEW

**Comment by jwscook** [comment]
Should have split these last commits into a new PR. Oh well.

**Comment by jwscook** [comment]
@claireh93 Could you review this PR please to make sure that I haven't blundered in a way that isn't caught by the tests?

**Comment by claireh93** [comment]
Thanks @jwscook! I'll take a look through this afternoon

**Review by claireh93 — APPROVED** [review]
Hi @jwscook, it looks good to me from looking at the code directly, but I've also had a play around with some of the examples just to check it is giving us the same kind of behaviour

**Comment by jwscook** [comment]
Great! I hope it helps speed a few things up.

**Comment by jwscook** [comment]
The github bot is saying that "Some checks haven't completed yet" when they have: the last remaining CI has passed https://travis-ci.org/github/ScottishCovidResponse/Simulation.jl/builds/695039860.

I'll rebase and merge.

**Pull request merged**
