### PR TITLE
Improve coverage

### LINKED ISSUE #461: Improve code coverage in testing
Particularly should focus on Epidemiology and Climate Pref sections of `src` - but Biodiversity also needs some attention.

### PR DESCRIPTION
**Pull request by claireh93**
Closes ScottishCovidResponse/SCRCIssueTracking#461

Improves test coverage across all subdirectories of src to 60%.

### CODE REVIEW

**Comment by claireh93** [comment]
@richardreeve @jwscook any idea why this is failing on mac but not linux? It seems to be something to do with the MPI build - I added some tests for the MPI biodiversity code.

**Comment by jwscook** [comment]
The ~~travis.yml~~ installMPI.sh script does different things for Linux compared to linux. I think that the caching for Mac osx had gone wrong, but it was never much of a time saver in the first place so we won't miss much by turning it off. I'll see if I can do it from my phone.

**Comment by claireh93** [comment]
Ahh thanks @jwscook, that's great!

**Comment by claireh93** [comment]
I think this can be merged into dev now @richardreeve?

**Review by richardreeve — APPROVED** [review]

**Pull request merged**
