### PR TITLE
Climate data into Scottish run

### LINKED ISSUE #11: Extend simplehabitatAE grids to read climate data
Relates #3 #10

### PR DESCRIPTION
**Pull request by claireh93**
Closes ScottishCovidResponse/SCRCIssueTracking#11

Addresses a few issues related to climate:

- Functions to download and process Met Office data, which resamples to BNG projection for now to be in line with Scottish Population data. Note that the climate data does not include the Shetland Islands. Also note that we need to add RCall back in to do this (Julia is not capable of working with rasters in the same way, as far as I'm aware).

- Functions to create 3D habitats that continuously update to the next timestep.

- Updated `Scotland_run` to run for the month of January with temperatures - very slow until #51 is merged.

### CODE REVIEW

**Comment by claireh93** [comment]
A few more updates but should be ready now

**Comment by claireh93** [comment]
Ah gosh I forgot that doing this climate processing with RCall means we have to have it installed on travis, is there any way we can get around this? @richard @jwscook any ideas?

**Comment by jwscook** [comment]
There was a time when the `.travis.yml` script did install R. It was right at the start of the RSE work

**Comment by claireh93** [comment]
It slowed down the travis runs quite a lot though didn't it? I can try to think of some kind of work around where I pre-process the climate data and have them uploaded to the ftp server as HDF5 files

**Comment by richardreeve** [comment]
I've reverted this to WIP, as I think we want to take out the RCall dependency before we merge it...

**Comment by claireh93** [comment]
Okay I have tried to get around this by loading RCall with `@requires` like with the PyCall examples - hopefully that works!

**Review by richardreeve — APPROVED** [review]

**Pull request merged**
