### PR TITLE
Simplify dependencies

### LINKED ISSUE #146: Lazy load optionally dependency packages e.g. MPI with Requires.jl
MPI isn't needed for serial or threaded runs, so it Requires.jl might speed up loading time if it used to configure the project to ignore MPI in these cases. If it doesn't speed things up, then scrap it and keep it simple.

### PR DESCRIPTION
**Pull request by mohdibntarek**
This PR: 
1. Makes MPI an optional dependency using Requires.
2. Makes Optim an optional dependency using Requires, defining and exporting `ClimatePref.fitBrownian` and `ClimatePref.fitLambda` only when Optim is loaded by the user. These 2 functions are not used anywhere else so I found it weird that we are loading the heavy Optim for just 2 unused functions.
3. Removes the dependency on Plots. It seems we were only using `Plots.px` in the src. This is a constant that is defined in `Plots` as `const px = Measures.AbsoluteLength(0.254)` so I copied that definition over and dropped `Plots` as a dependency, depending on the much lighter `Measures` instead. `PlotlyJS` was also not used so I removed it from the Project.toml file.
4. Removes SpatialEcology from the deps because it was not used.

This PR fixes https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/146 but does more than that. Tests pass locally so let's see what Travis says.

### CODE REVIEW

**Comment by mohdibntarek** [comment]
I don't have MPI on my system, so someone please check how much the loading time has dropped by.

**Comment by mohdibntarek** [comment]
Compared to https://travis-ci.org/github/ScottishCovidResponse/Simulation.jl/builds/684238943, the tests here seem to finish in less than half the time, so 🎉

**Comment by mohdibntarek** [comment]
The loading time is still about 90 seconds on my system which is still long but we can look at ways of reducing those in future PRs. In particular, we can consider not using JuliaDB but only the bits and pieces that we need from JuliaDB, e.g. table loading and wrangling, or even better replacing it with the lighter DataFrames which is also used in Simulation.jl.

**Comment by claireh93** [comment]
Thanks for cleaning all of that up Mohamed, I think a lot of those dependencies have worked their way in and out of the package over the years! I can't approve because I requested the review but hopefully @jwscook or @richardreeve can

**Review by jwscook — APPROVED** [review]
Very nice - I've not used Requires.jl before, so I learned something new.

**Pull request merged**
