### PR TITLE
Fix up examples folder

### PR DESCRIPTION
**Pull request by claireh93**
Addressing ScottishCovidResponse/SCRCIssueTracking#212:

- Examples folder now includes a run file for Scotland and UK - 1 year with daily updates at 10km grid resolution, with decadal age classes.

- Have also kept the original SEI2HRD example for now - without age classes and running at 1km.

- Fixed some bugs in the indexing and parameter set up for SEI2HRD.

### CODE REVIEW

**Review by richardreeve — APPROVED** [review]
I'm assuming these bugfixes are correct in EpiGenerate.jl, but I need to go through this code in detail this week to really understand it. I've fixed a couple of small things in the examples.

**Comment by richardreeve** [comment]
Incidentally, there's a bug in how you're generating Binomial random numbers here, but this is going to be addressed in #37.

**Comment by claireh93** [comment]
Yes I think there's no small amount of confusion with the indices - for example, now the examples/tests are set up to have dispersal vectors that are only # human categories long - hence why the virus movement operates over j, and not j+1. I think this will benefit from separate epilists for humans and viruses like we discussed.

**Comment by richardreeve** [comment]
Do you want to just merge this now?

**Pull request merged**
