### PR TITLE
benchmark for multi-thread

### PR DESCRIPTION
**Pull request by wytbella**
to address https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/6

Is this what you are after? Or you want more detailed multi-thread benchmarking on specific functions?

### CODE REVIEW

**Comment by claireh93** [comment]
I think we can probably merge this for now and then think about ScottishCovidResponse/SCRCIssueTracking#140 - unfortunately I can't review as I added the admins to this PR.

**Comment by richardreeve** [comment]
Wow. I see why you wanted smaller benchmarks now! I'm going to have to finish this tomorrow morning...

**Review by richardreeve — APPROVED** [review]
This all looks good to me and works well. I agree with @claireh93 that we should merge this and then move on to the smaller benchmarks now I really appreciate how long these take! We also need to set up documentation for the package more generally (as a separate issue too) which will contain information on how to run the benchmarks, for instance.

**Comment by richardreeve** [comment]
@claireh93 I've approved this if you want to merge it.

**Pull request merged**
