### PR TITLE
Ar/travis rebase

### PR DESCRIPTION
**Pull request by AlexRobson**
Updates .travis.yml to correctly build (for 1.4)
    Includes ScottishCovidResponse#2

1.0.5 is set to allow failures for now.

### CODE REVIEW

**Comment by jwscook** [comment]
There are some changes here in some of the `test/*.jl` files - are these intentional? I'm surprised that they aren't already in `master` @claireh93 can you comment on whether these changes are good to be merged in?

**Comment by AlexRobson** [comment]
It includes this: https://github.com/ScottishCovidResponse/Simulation.jl/pull/2/files

Which I believe isn't in master. [It was an MR into this branch]. Ideally, this MR would be just the travis related changes. For clarity, that could be remade as a separate MR for master so only the travis changes show here.

**Comment by claireh93** [comment]
Ah yes those were some changes to tests I made to help Alex's travis run work properly (I hadn't realised some of those weren't fully up-to-date). Probably makes sense as a separate PR for those then? I need them for the tests I'm working on at the moment.

**Comment by jwscook** [comment]
It's not 100% ideal and separating these into a separate PR would be neater, but I think a pragmatic solution is to accept the PR as is. We are against the clock somewhat after all.

It won't make any problems for you @claireh93 to PR that branch in later, so I'm happy to merge if you are.

**Comment by claireh93** [comment]
Sounds good!

**Comment by jwscook** [comment]
Great work - thanks very much @AlexRobson

**Pull request merged**
