### PR TITLE
WIP: improve threading

### PR DESCRIPTION
**Pull request by jwscook**
SCRC-468

Prettty simple change, but I see a factor of 2 improvement in performance on my 6core i9 laptop.

### CODE REVIEW

**Comment by jwscook** [comment]
I spoke too soon. The tests will fail.

**Comment by jwscook** [comment]
This is made more complicated because `epi.cache.virusmigration` is mutated in `virusmove!` which itself is called in the inner loop of `virusupdate!`.

**Comment by jwscook** [comment]
My machine might be too noisy to test if doing this after the threaded loop is faster after all.

```
for i in 1:dims
   vm = sum(@view epi.cache.virusmigration[:, i])
   nm = sum(@view epi.cache.virusdecay[:, i])
   virus(epi.abundances)[1, i] += nm + vm
   epi.cache.virusmigration[1, i] += vm
end
```
By which I mean adding the above below  https://github.com/ScottishCovidResponse/Simulation.jl/blob/82c1fbd972d8075204684c5f0761a1bed6bbf91d/src/Epidemiology/EpiGenerate.jl#L68

**Comment by claireh93** [comment]
Hi @jwscook you might want to check out the new merge from Bella, which has changed the update loop somewhat, and also #51 where I have changed things fairly considerably again! Does that make any impact on the threading issues you noticed?

**Comment by jwscook** [comment]
On 2 threads 35% is spent waiting.
On 4 threads 44% is spent waiting.

**Comment by jwscook** [comment]
@claireh93 why is that `size(epi.cache.virusmigration) = (80, 317856)` and `(length(classes), dims) = (30, 317856)`? Shouldn't `size(epi.cache.virusmigration, 1) == length(classes)` be true?
Edit: Nevermind - I see the new line `classes = findall(blah blah)`

**Comment by claireh93** [comment]
Wow that's a lot of time spent waiting! Out of interest, what tools do you use to check that?

**Comment by jwscook** [comment]
Profile.jl and https://github.com/tkluck/StatProfilerHTML.jl

**Comment by richardreeve** [comment]
I don't understand what the waiting is for, I have to admit. Does `Threads.@threads` just split up the loop equally and not distribute the elements on the fly? If so, maybe we have the problem we anticipated having with MPI - some threads are just looping over water?

**Comment by jwscook** [comment]
I'm not sure anymore. According to the julia discourse (link forgotten) and a couple of other places, profiling with threaded code isn't very reliable. So it might be best just to use timings as a guide.

I've developed a different way of writing this calculation that doesn't require two `@threads for`, so hopefully some work from the first and second loop can be done concurrently, thereby eliding one of the `wait`s.

**Comment by jwscook** [comment]
@claireh93, @richardreeve I've written a Minimum Working Example of the new algorithm as a gist [here](https://gist.github.com/jwscook/2a9f080a96a01d62a805a9f0f2b64244)

**Comment by richardreeve** [comment]
It would definitely be useful to have a chat about this... are you free later? @claireh93 @jwscook

**Comment by jwscook** [comment]
I'm free now @claireh93 @richardreeve until 3ish

**Comment by jwscook** [comment]
I wrote a MWE here https://gist.github.com/jwscook/2a9f080a96a01d62a805a9f0f2b64244

**Comment by claireh93** [comment]
Cool, I have some time 2-3ish

**Comment by jwscook** [comment]
Looks like I might have added / revealed a bug in 59423fd

@claireh93 which is correct: [for iter in classes](https://github.com/ScottishCovidResponse/Simulation.jl/blob/59423fdedf35223575a680677b8a709f77b0c1aa/src/Epidemiology/EpiGenerate.jl#L148) or [for iter in 1:classes](https://github.com/ScottishCovidResponse/Simulation.jl/blob/077362c924ea8880dee4a46e803fb4da940594cc/src/Epidemiology/EpiGenerate.jl#L124)?

**Comment by jwscook** [comment]
@claireh93 my mistake. `classes` is an `Int` in `classupdate!`, and `Vector` in `virusupdate!`.

Looks like 59423fd is a bug.

**Comment by claireh93** [comment]
Hi James, was just chatting to Richard about the environmental decay happening for each class - the parameters are set to zero for all but one class to prevent this from happening too often. So it looks like once this is merged, we could pull that completely out from the loop and save some more time - I'm happy to make that change along with some others related to mixing? Also I think we can drop `notclasses` because they don't generate or move any virus, so these will be all zeros

**Comment by jwscook** [comment]
Ok - shall we merge this branch into dev now, or do you want to make the changes you just described first?

BTW the CI currently says that this one https://travis-ci.org/github/ScottishCovidResponse/Simulation.jl/builds/701611272 hasn't completed, but it has and everything passed.

**Comment by claireh93** [comment]
I think we can merge now and make the changes in another PR - I'll approve it now!

**Review by claireh93 — APPROVED** [review]

**Pull request merged**
